apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pern-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Akashkayande/jenkins-eks-argocd.git
    targetRevision: main
    path: helm/pern
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: pern-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
