apiVersion: v1
kind: Service
metadata:
  name: backend-canary-service
  namespace: {{ .Values.namespace }}
  labels: 
    app: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
