apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.canary.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.canary.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
        track: canary
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.canary.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.canary.requests.cpu }}
              memory: {{ .Values.frontend.resources.canary.requests.memory }}
            limits:
              cpu: {{ .Values.frontend.resources.canary.limits.cpu }}
              memory: {{ .Values.frontend.resources.canary.limits.memory }}

