apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  PORT: {{ .Values.backend.secrets.PORT }}
  DATABASE_URL: {{ .Values.backend.secrets.DATABASE_URL }}
  CLERK_PUBLISHABLE_KEY: {{ .Values.backend.secrets.CLERK_PUBLISHABLE_KEY }}
  CLERK_SECRET_KEY: {{ .Values.backend.secrets.CLERK_SECRET_KEY }}
  GEMINI_API_KEY: {{ .Values.backend.secrets.GEMINI_API_KEY }}
  CLIPDROP_API_KEY: {{ .Values.backend.secrets.CLIPDROP_API_KEY }}
  CLOUDINARY_CLOUD_NAME: {{ .Values.backend.secrets.CLOUDINARY_CLOUD_NAME }}
  CLOUDINARY_API_KEY: {{ .Values.backend.secrets.CLOUDINARY_API_KEY }}
  CLOUDINARY_API_SECRET: {{ .Values.backend.secrets.CLOUDINARY_API_SECRET }}